In [1]:
import pandas as pd
import numpy as np

In [2]:
# load dataset
df = pd.read_csv("raw/spotify_3.csv")

In [4]:
# print columns
print("Spotify 3 Columns: \n", df.columns.tolist())

Spotify 3 Columns:
 ['track_id', 'track_name', 'track_number', 'track_popularity', 'track_duration_ms', 'explicit', 'artist_name', 'artist_popularity', 'artist_followers', 'artist_genres', 'album_id', 'album_name', 'album_release_date', 'album_total_tracks', 'album_type']

In [5]:
# check data types
print(df.dtypes)

track_id               object
track_name             object
track_number            int64
track_popularity        int64
track_duration_ms       int64
explicit                 bool
artist_name            object
artist_popularity     float64
artist_followers      float64
artist_genres          object
album_id               object
album_name             object
album_release_date     object
album_total_tracks      int64
album_type             object
dtype: object

In [6]:
# standardize release date to only include years
df = df[df["album_release_date"] != "0000"]
df["release_year"] = pd.to_datetime(df["album_release_date"], format = "mixed").dt.year

In [7]:
# filter year between 2016 and 2020
df = df[(df["release_year"] <= 2020) & (df["release_year"] >= 2016)]

In [8]:
df.head()

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,release_year
6,41zXlQxzTi6cGAjpOXyLYH,idontwannabeyouanymore,2,78,203569,False,Billie Eilish,90.0,118692183.0,[],7fRrTyKvE4Skh93v97gtcU,dont smile at me,2017-12-22,9,single,2017
9,0qUcpOOna3kkrwfqky85e1,Eyes Blue Like The Atlantic (feat. Subvrbs),1,63,154599,False,Sista Prod,48.0,68226.0,[],5UYjxc4HIYeesKS0WJlhEI,Eyes Blue Like The Atlantic (feat. Subvrbs),2020-07-20,1,single,2020
17,7KXjTSCq5nL1LoYtL7XAwS,HUMBLE.,8,83,177000,True,Kendrick Lamar,89.0,44577310.0,"['hip hop', 'west coast hip hop']",4eLPsYPBmXABThSJ821sqY,DAMN.,2017-04-14,14,album,2017
18,3WzNy6b7PZIlWbiyZcVj8d,I Put a Spell on You,1,50,164522,False,Sylvia Black,32.0,3581.0,[],5yxIeBwhxzGOOzinVpjMsg,I Put a Spell on You,2018-11-14,1,single,2018
20,2YFc0r6PUWDAeE38vJnCxR,ghost girl,5,72,173946,True,Lil Peep,82.0,15684530.0,"['emo rap', 'cloud rap']",2tLt6wYVuseWCe6IwDSlTm,crybaby,2016-06-10,10,album,2016

In [9]:
# standardize artist_genres

df["artist_genres"] = df["artist_genres"].str.translate({ord('['): None,
                                                        ord(']'): None,
                                                        ord('\''): None})

# check for missing values and empty strings
print(df['artist_genres'].isna().sum(), 'NaN values')
print((df['artist_genres'] == '').sum(), 'empty strings')

0 NaN values
1332 empty strings

In [10]:
# remove rows with empty strings
df = df[df["artist_genres"] != '']

In [11]:
# filter columns needed
df = df[["track_id", "track_name", "track_popularity", "track_duration_ms", "artist_name", "artist_popularity", "artist_followers", 
                "artist_genres", "album_name", "release_year"]]

In [12]:
df.head()

,track_id,track_name,track_popularity,track_duration_ms,artist_name,artist_popularity,artist_followers,artist_genres,album_name,release_year
17,7KXjTSCq5nL1LoYtL7XAwS,HUMBLE.,83,177000,Kendrick Lamar,89.0,44577310.0,"hip hop, west coast hip hop",DAMN.,2017
20,2YFc0r6PUWDAeE38vJnCxR,ghost girl,72,173946,Lil Peep,82.0,15684530.0,"emo rap, cloud rap",crybaby,2016
22,3mPn97K8T07095yVSpYr6d,tonight you belong to me (feat. Paul & Carmell...,45,86040,Christina Perri,71.0,4307803.0,soft pop,songs for carmella: lullabies & sing-a-longs,2019
32,6u7gmPOz7pzzaeR9xSBpsR,my hair,62,158436,Ariana Grande,90.0,107374593.0,pop,Positions,2020
47,5Pc594FhDA2Fa2prE75GT0,Pretty Please,50,194607,Dua Lipa,85.0,46886554.0,pop,Future Nostalgia,2020

In [13]:
df.shape

(1057, 10)

In [14]:
# save clean dataset
df.to_csv("processed/spotify_track_info.csv", index=False)