In [1]:
# load libaries

import pandas as pd
import numpy as np

In [2]:
# load datasets

spotify_1 = pd.read_csv("raw/spotify_1.csv")
spotify_2 = pd.read_csv("raw/spotify_2.csv")

# list columns of all three datasets
print("Spotify 1 Columns: \n", spotify_1.columns.tolist(), "\n Spotify 2 Columns:\n", spotify_2.columns.tolist())

Spotify 1 Columns:
 ['id', 'artist_names', 'track_name', 'source', 'key', 'mode', 'time_signature', 'danceability', 'energy', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'loudness', 'tempo', 'duration_ms', 'weeks_on_chart', 'streams']
 Spotify 2 Columns:
 ['valence', 'year', 'acousticness', 'artists', 'danceability', 'duration_ms', 'energy', 'explicit', 'id', 'instrumentalness', 'key', 'liveness', 'loudness', 'mode', 'name', 'popularity', 'release_date', 'speechiness', 'tempo']

In [3]:
# renaming columns for standardizing
spotify_1 = spotify_1.rename(columns={"id": "track_id"})
spotify_2 = spotify_2.rename(columns={"id": "track_id"})

spotify_1 = spotify_1.rename(columns={"artist_names": "artist_name"})
spotify_2 = spotify_2.rename(columns={"artists": "artist_name"})

spotify_2 = spotify_2.rename(columns={"name": "track_name"})

print(spotify_1.columns, spotify_2.columns)

print(spotify_1.shape, spotify_2.shape)

Index(['track_id', 'artist_name', 'track_name', 'source', 'key', 'mode',
       'time_signature', 'danceability', 'energy', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'loudness',
       'tempo', 'duration_ms', 'weeks_on_chart', 'streams'],
      dtype='object') Index(['valence', 'year', 'acousticness', 'artist_name', 'danceability',
       'duration_ms', 'energy', 'explicit', 'track_id', 'instrumentalness',
       'key', 'liveness', 'loudness', 'mode', 'track_name', 'popularity',
       'release_date', 'speechiness', 'tempo'],
      dtype='object')
(6513, 19) (170653, 19)

In [4]:
# CLEANING: Spotify 1 - Spotify Top Songs And Audio Features

# check data types
print(spotify_1.dtypes)

# check for missing values
missing_values_1 = spotify_1.isnull().sum()
print("Missing values:\n", missing_values_1)

# drop missing values
spotify_1 = spotify_1.dropna()

# check for duplicates
spotify_1 = spotify_1.drop_duplicates()
print("Shapes after dropping duplicates:", spotify_1.shape)

spotify_1.sample(5)

track_id             object
artist_name          object
track_name           object
source               object
key                  object
mode                 object
time_signature       object
danceability        float64
energy              float64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
loudness            float64
tempo               float64
duration_ms           int64
weeks_on_chart        int64
streams               int64
dtype: object
Missing values:
 track_id            0
artist_name         0
track_name          0
source              0
key                 0
mode                0
time_signature      0
danceability        0
energy              0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
loudness            0
tempo               0
duration_ms         0
weeks_on_chart      0
streams             0
dtype: int64
Shapes after dropping duplicates: (6513, 19)

,track_id,artist_name,track_name,source,key,mode,time_signature,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,loudness,tempo,duration_ms,weeks_on_chart,streams
1463,1mT47pKLXUwPYGwB91GcNz,"KAROL G, Maluma",Créeme,UMLE - Latino,F#/Gb,Major,4 beats,0.715,0.872,0.0547,0.1540,0.000146,0.1100,0.682,-3.501,96.939,212493,19,104018594
4413,5FOCkGt7bp22nBVfQ4WSIT,Anitta,Indecente,WM Brazil,G,Major,4 beats,0.874,0.602,0.1270,0.1600,0.000842,0.0960,0.587,-5.118,127.997,205188,3,11902809
803,0y60itmpH0aPKsFiGxmtnh,WILLOW,Wait a Minute!,Roc Nation W Smith P&D,D#/Eb,Minor,4 beats,0.764,0.705,0.0278,0.0371,0.000019,0.0943,0.672,-5.279,101.003,196520,24,214021308
2407,2rFsFjq0D9JAmc0APpCO6P,"Internet Money, Trippie Redd, Diplo, Juice WRLD",Blastoff (feat. Juice WRLD),Internet Money Records / 10K Projects,F,Major,4 beats,0.761,0.517,0.0927,0.1140,0.000000,0.1570,0.460,-6.916,147.912,174730,3,19385163
2169,2ZUJsR8HEktit58X6FuPQM,Kanye West,Heaven and Hell,Rock The World/IDJ/Kanye LP7,C,Minor,4 beats,0.764,0.422,0.1190,0.0409,0.000000,0.1520,0.268,-7.265,82.986,145301,2,20980096

In [5]:
# summary
spotify_1.describe()

,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,loudness,tempo,duration_ms,weeks_on_chart,streams
count,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6.513000e+03
mean,0.681731,0.636522,0.121933,0.236761,0.012469,0.180168,0.492412,-6.350667,122.117244,202566.684170,13.614924,1.089647e+08
std,0.141787,0.164813,0.113441,0.244784,0.075151,0.138054,0.227001,2.536114,29.416097,49199.592333,24.084051,2.276695e+08
min,0.150000,0.021800,0.023200,0.000008,0.000000,0.019700,0.032000,-34.475000,46.718000,30133.000000,1.000000,2.525159e+06
25%,0.591000,0.534000,0.044000,0.044400,0.000000,0.097400,0.316000,-7.564000,98.007000,173038.000000,1.000000,8.695060e+06
50%,0.698000,0.651000,0.072200,0.145000,0.000000,0.124000,0.489000,-5.983000,120.034000,198367.000000,4.000000,2.712856e+07
75%,0.785000,0.759000,0.163000,0.356000,0.000041,0.219000,0.669000,-4.673000,142.025000,226003.000000,16.000000,9.951456e+07
max,0.985000,0.989000,0.966000,0.994000,0.953000,0.977000,0.982000,1.509000,212.117000,690732.000000,367.000000,3.528450e+09

In [6]:
# filter for columns related to research question due to database constraints
cleaned_spotify_1 = spotify_1[["track_id", "danceability", "valence", "energy", "tempo", "duration_ms", "streams"]]
print(cleaned_spotify_1.shape)

(6513, 7)

In [7]:
# standardize so all decimals are rounded to 3 decimal points
cleaned_spotify_1[["danceability", "valence", "energy", "tempo"]] = cleaned_spotify_1[["danceability", "valence", "energy", "tempo"]].round(3)

cleaned_spotify_1.head()

/tmp/ipykernel_5769/3987959647.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_spotify_1[["danceability", "valence", "energy", "tempo"]] = cleaned_spotify_1[["danceability", "valence", "energy", "tempo"]].round(3)

,track_id,danceability,valence,energy,tempo,duration_ms,streams
0,000xQL6tZNLJzIrtIgxqSl,0.748,0.524,0.627,120.963,188491,107527761
1,003eoIwxETJujVWmNFMoZy,0.353,0.437,0.755,191.153,193680,9944865
2,003vvx7Niy0yvhvHt4a68B,0.352,0.236,0.911,148.033,222973,512388123
3,00B7TZ0Xawar6NZ00JFomN,0.620,0.665,0.625,167.911,284856,11985346
4,00Blm7zeNqgYLPtW6zg8cj,0.687,0.688,0.781,97.014,193507,301860377

In [8]:
# CLEANING: Spotify 2 - Spotify Dataset 1921-2020 
# check data types
print(spotify_2.dtypes)

# check for missing values
missing_values_2 = spotify_2.isnull().sum()
print("Missing values:\n", missing_values_2)

# drop missing values
spotify_2 = spotify_2.dropna()

# check for duplicates
spotify_2 = spotify_2.drop_duplicates()
print("Shapes after dropping duplicates:", spotify_2.shape)

spotify_2.sample(5)

valence             float64
year                  int64
acousticness        float64
artist_name          object
danceability        float64
duration_ms           int64
energy              float64
explicit              int64
track_id             object
instrumentalness    float64
key                   int64
liveness            float64
loudness            float64
mode                  int64
track_name           object
popularity            int64
release_date         object
speechiness         float64
tempo               float64
dtype: object
Missing values:
 valence             0
year                0
acousticness        0
artist_name         0
danceability        0
duration_ms         0
energy              0
explicit            0
track_id            0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
track_name          0
popularity          0
release_date        0
speechiness         0
tempo               0
dtype: int64
Shapes after dropping duplicates: (170653, 19)

,valence,year,acousticness,artist_name,danceability,duration_ms,energy,explicit,track_id,instrumentalness,key,liveness,loudness,mode,track_name,popularity,release_date,speechiness,tempo
42532,0.4190,1946,0.993,['Hesen Zîrek'],0.265,307409,0.5490,0,1kZJFYi2rqcVk1GMzfcO6M,0.912000,0,0.1180,-7.432,0,Eman Sebrî,0,1946,0.0376,88.277
67511,0.9300,1982,0.483,['Paul Davis'],0.710,220867,0.5860,0,3dgpLSZlacfOVPAjiXRIfS,0.000000,2,0.0556,-5.783,0,'65 Love Affair - Single Version,35,1982,0.0275,156.542
81389,0.0881,1965,0.992,"['Frédéric Chopin', 'Arthur Rubinstein']",0.240,406947,0.0494,0,0pA5lxXSQ61cQ97L2XsSoq,0.879000,6,0.1110,-23.896,1,"Nocturnes, Op. 9: No. 3 in B Major",27,1965,0.0411,69.668
148425,0.9660,1984,0.145,['Diego Verdaguer'],0.606,177894,0.8820,0,5VKymQ4msDNpFgDnFhIxau,0.000013,10,0.0974,-8.439,0,Usted Qué Haría?,38,1984-04-01,0.0426,180.056
135493,0.5420,1993,0.109,['Souls Of Mischief'],0.788,230813,0.6230,0,2H3Ee8gYFvCZ2ivuOl5wwI,0.000036,10,0.1420,-12.298,0,Make Your Mind Up,36,1993-02-13,0.3570,93.567

In [9]:
# summary
spotify_2.describe()

,valence,year,acousticness,danceability,duration_ms,energy,explicit,instrumentalness,key,liveness,loudness,mode,popularity,speechiness,tempo
count,170653.000000,170653.000000,170653.000000,170653.000000,1.706530e+05,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000
mean,0.528587,1976.787241,0.502115,0.537396,2.309483e+05,0.482389,0.084575,0.167010,5.199844,0.205839,-11.467990,0.706902,31.431794,0.098393,116.861590
std,0.263171,25.917853,0.376032,0.176138,1.261184e+05,0.267646,0.278249,0.313475,3.515094,0.174805,5.697943,0.455184,21.826615,0.162740,30.708533
min,0.000000,1921.000000,0.000000,0.000000,5.108000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,-60.000000,0.000000,0.000000,0.000000,0.000000
25%,0.317000,1956.000000,0.102000,0.415000,1.698270e+05,0.255000,0.000000,0.000000,2.000000,0.098800,-14.615000,0.000000,11.000000,0.034900,93.421000
50%,0.540000,1977.000000,0.516000,0.548000,2.074670e+05,0.471000,0.000000,0.000216,5.000000,0.136000,-10.580000,1.000000,33.000000,0.045000,114.729000
75%,0.747000,1999.000000,0.893000,0.668000,2.624000e+05,0.703000,0.000000,0.102000,8.000000,0.261000,-7.183000,1.000000,48.000000,0.075600,135.537000
max,1.000000,2020.000000,0.996000,0.988000,5.403500e+06,1.000000,1.000000,1.000000,11.000000,1.000000,3.855000,1.000000,100.000000,0.970000,243.507000

In [31]:
# research questions only concerns songs from 2016 onwards, filter for these specific years to meet limit of database
filtered_spotify_2 = spotify_2[spotify_2["year"] >= 2016]

# filter for columns related to research question due to database constraints
cleaned_spotify_2 = filtered_spotify_2[["track_id", "danceability", "valence", "energy", "tempo", "duration_ms", "year", "popularity"]]

# round to 3 decimals
cleaned_spotify_2[["danceability", "valence", "energy", "tempo"]] = cleaned_spotify_2[["danceability", "valence", "energy", "tempo"]].round(3)

cleaned_spotify_2.head()
print(cleaned_spotify_2.shape)
print(cleaned_spotify_2.describe())

(9871, 8)
       danceability      valence       energy        tempo    duration_ms  \
count   9871.000000  9871.000000  9871.000000  9871.000000    9871.000000
mean       0.643986     0.451670     0.602370   120.527127  206329.457400
std        0.171375     0.232385     0.205164    30.764615   56845.248426
min        0.000000     0.000000     0.000000     0.000000   30579.000000
25%        0.546000     0.272000     0.480500    96.133000  174844.000000
50%        0.664000     0.442000     0.622000   120.078000  202000.000000
75%        0.768000     0.621000     0.749000   141.915000  230543.500000
max        0.985000     0.982000     1.000000   220.099000  732554.000000

              year   popularity
count  9871.000000  9871.000000
mean   2018.042853    63.219228
std       1.395857    16.047364
min    2016.000000     0.000000
25%    2017.000000    60.000000
50%    2018.000000    65.000000
75%    2019.000000    71.000000
max    2020.000000   100.000000

/tmp/ipykernel_5769/1443021529.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_spotify_2[["danceability", "valence", "energy", "tempo"]] = cleaned_spotify_2[["danceability", "valence", "energy", "tempo"]].round(3)

In [32]:
# check overlap between spotify 1 and spotify 2
overlap = cleaned_spotify_1[cleaned_spotify_1["track_id"].isin(cleaned_spotify_2["track_id"])].shape[0]
print(overlap)

1858

In [37]:
spotify_audible_features = cleaned_spotify_1.merge(cleaned_spotify_2[["track_id", "year", "popularity"]], on=['track_id'], how="inner")
print(spotify_audible_features.shape)
print(spotify_audible_features.describe())

(1858, 9)
       danceability      valence       energy        tempo    duration_ms  \
count   1858.000000  1858.000000  1858.000000  1858.000000    1858.000000
mean       0.699266     0.475125     0.621809   122.878793  205194.045210
std        0.136924     0.219766     0.159170    30.049936   45178.975007
min        0.153000     0.036000     0.028000    54.747000   37640.000000
25%        0.618000     0.303000     0.524000    97.812500  178006.250000
50%        0.716500     0.467000     0.632000   120.511500  202193.000000
75%        0.797000     0.645000     0.740000   144.928750  228104.000000
max        0.980000     0.970000     0.972000   207.476000  577199.000000

            streams         year   popularity
count  1.858000e+03  1858.000000  1858.000000
mean   1.503641e+08  2018.562433    74.482777
std    2.985478e+08     1.194868     7.533588
min    2.580512e+06  2016.000000    54.000000
25%    1.215400e+07  2018.000000    69.000000
50%    4.221403e+07  2019.000000    74.000000
75%    1.583216e+08  2020.000000    80.000000
max    3.528450e+09  2020.000000   100.000000

In [38]:
spotify_audible_features.isnull().sum()

track_id        0
danceability    0
valence         0
energy          0
tempo           0
duration_ms     0
streams         0
year            0
popularity      0
dtype: int64

In [39]:
# save cleaned dataset to csv
spotify_audible_features.to_csv("processed/spotify_audible_features.csv", index=False)