In [47]:
# load libaries

import pandas as pd
import numpy as np

In [48]:
# load datasets

spotify_1 = pd.read_csv("raw/spotify_1.csv")
spotify_2 = pd.read_csv("raw/spotify_2.csv")

# list columns of all three datasets
print("Spotify 1 Columns: \n", spotify_1.columns.tolist(), "\n Spotify 2 Columns:\n", spotify_2.columns.tolist())

Spotify 1 Columns:
 ['id', 'artist_names', 'track_name', 'source', 'key', 'mode', 'time_signature', 'danceability', 'energy', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'loudness', 'tempo', 'duration_ms', 'weeks_on_chart', 'streams']
 Spotify 2 Columns:
 ['valence', 'year', 'acousticness', 'artists', 'danceability', 'duration_ms', 'energy', 'explicit', 'id', 'instrumentalness', 'key', 'liveness', 'loudness', 'mode', 'name', 'popularity', 'release_date', 'speechiness', 'tempo']

In [49]:
# renaming columns for standardizing
spotify_1 = spotify_1.rename(columns={"id": "track_id"})
spotify_2 = spotify_2.rename(columns={"id": "track_id"})

spotify_1 = spotify_1.rename(columns={"artist_names": "artist_name"})
spotify_2 = spotify_2.rename(columns={"artists": "artist_name"})

spotify_2 = spotify_2.rename(columns={"name": "track_name"})

print(spotify_1.columns, spotify_2.columns)

print(spotify_1.shape, spotify_2.shape)

Index(['track_id', 'artist_name', 'track_name', 'source', 'key', 'mode',
       'time_signature', 'danceability', 'energy', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'loudness',
       'tempo', 'duration_ms', 'weeks_on_chart', 'streams'],
      dtype='object') Index(['valence', 'year', 'acousticness', 'artist_name', 'danceability',
       'duration_ms', 'energy', 'explicit', 'track_id', 'instrumentalness',
       'key', 'liveness', 'loudness', 'mode', 'track_name', 'popularity',
       'release_date', 'speechiness', 'tempo'],
      dtype='object')
(6513, 19) (170653, 19)

In [50]:
# CLEANING: Spotify 1 - Spotify Top Songs And Audio Features

# check data types
print(spotify_1.dtypes)

# check for missing values
missing_values_1 = spotify_1.isnull().sum()
print("Missing values:\n", missing_values_1)

# drop missing values
spotify_1 = spotify_1.dropna()

# check for duplicates
spotify_1 = spotify_1.drop_duplicates()
print("Shapes after dropping duplicates:", spotify_1.shape)

spotify_1.sample(5)

track_id             object
artist_name          object
track_name           object
source               object
key                  object
mode                 object
time_signature       object
danceability        float64
energy              float64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
loudness            float64
tempo               float64
duration_ms           int64
weeks_on_chart        int64
streams               int64
dtype: object
Missing values:
 track_id            0
artist_name         0
track_name          0
source              0
key                 0
mode                0
time_signature      0
danceability        0
energy              0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
loudness            0
tempo               0
duration_ms         0
weeks_on_chart      0
streams             0
dtype: int64
Shapes after dropping duplicates: (6513, 19)

,track_id,artist_name,track_name,source,key,mode,time_signature,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,loudness,tempo,duration_ms,weeks_on_chart,streams
3186,3nqQXoyQOWXiESFLlDF1hG,"Sam Smith, Kim Petras",Unholy (feat. Kim Petras),Capitol Records UK / EMI,D,Major,4 beats,0.714,0.472,0.0864,0.0130,0.000005,0.266,0.238,-7.375,131.121,156943,18,735600621
6106,7JDbfYUHjDzQPFSDh5lzGs,Lady Gaga,Enigma,Interscope,C,Major,4 beats,0.669,0.804,0.0360,0.0306,0.000000,0.694,0.184,-4.035,116.001,179760,1,7695566
3529,4EKZsrsCKyqr64FBHLc0DU,"KAROL G, Maluma",Créeme,UMLE - Latino,F#/Gb,Major,4 beats,0.715,0.874,0.0548,0.1260,0.000162,0.105,0.652,-3.576,96.995,214293,21,8664658
1023,1DcxnVNFAyVl2sDQ646pXS,KEVIN ROLDAN,PPP,UMLE - Latino,E,Major,4 beats,0.786,0.650,0.1090,0.3630,0.000082,0.122,0.712,-6.839,92.975,129040,15,74473493
5364,6RyuoOJXNzlVWpfC5xQyeI,"Omar Montes, Bad Gyal",Alocao (With Bad Gyal),Bad Gyal Aftercluv/Interscope,B,Minor,4 beats,0.673,0.752,0.0567,0.2140,0.000002,0.106,0.699,-4.705,178.005,209320,2,10592239

In [51]:
# summary
spotify_1.describe()

,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,loudness,tempo,duration_ms,weeks_on_chart,streams
count,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6.513000e+03
mean,0.681731,0.636522,0.121933,0.236761,0.012469,0.180168,0.492412,-6.350667,122.117244,202566.684170,13.614924,1.089647e+08
std,0.141787,0.164813,0.113441,0.244784,0.075151,0.138054,0.227001,2.536114,29.416097,49199.592333,24.084051,2.276695e+08
min,0.150000,0.021800,0.023200,0.000008,0.000000,0.019700,0.032000,-34.475000,46.718000,30133.000000,1.000000,2.525159e+06
25%,0.591000,0.534000,0.044000,0.044400,0.000000,0.097400,0.316000,-7.564000,98.007000,173038.000000,1.000000,8.695060e+06
50%,0.698000,0.651000,0.072200,0.145000,0.000000,0.124000,0.489000,-5.983000,120.034000,198367.000000,4.000000,2.712856e+07
75%,0.785000,0.759000,0.163000,0.356000,0.000041,0.219000,0.669000,-4.673000,142.025000,226003.000000,16.000000,9.951456e+07
max,0.985000,0.989000,0.966000,0.994000,0.953000,0.977000,0.982000,1.509000,212.117000,690732.000000,367.000000,3.528450e+09

In [52]:
# filter for columns related to research question due to database constraints
cleaned_spotify_1 = spotify_1[["track_id", "danceability", "valence", "energy", "tempo", "streams"]]
print(cleaned_spotify_1.shape)

(6513, 6)

In [53]:
# standardize so all decimals are rounded to 3 decimal points
cleaned_spotify_1[["danceability", "valence", "energy", "tempo"]] = cleaned_spotify_1[["danceability", "valence", "energy", "tempo"]].round(3)

cleaned_spotify_1.head()

/tmp/ipykernel_5769/3987959647.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_spotify_1[["danceability", "valence", "energy", "tempo"]] = cleaned_spotify_1[["danceability", "valence", "energy", "tempo"]].round(3)

                 track_id  danceability  valence  energy    tempo    streams
0  000xQL6tZNLJzIrtIgxqSl         0.748    0.524   0.627  120.963  107527761
1  003eoIwxETJujVWmNFMoZy         0.353    0.437   0.755  191.153    9944865
2  003vvx7Niy0yvhvHt4a68B         0.352    0.236   0.911  148.033  512388123
3  00B7TZ0Xawar6NZ00JFomN         0.620    0.665   0.625  167.911   11985346
4  00Blm7zeNqgYLPtW6zg8cj         0.687    0.688   0.781   97.014  301860377

In [54]:
# CLEANING: Spotify 2 - Spotify Dataset 1921-2020 
# check data types
print(spotify_2.dtypes)

# check for missing values
missing_values_2 = spotify_2.isnull().sum()
print("Missing values:\n", missing_values_2)

# drop missing values
spotify_2 = spotify_2.dropna()

# check for duplicates
spotify_2 = spotify_2.drop_duplicates()
print("Shapes after dropping duplicates:", spotify_2.shape)

spotify_2.sample(5)

valence             float64
year                  int64
acousticness        float64
artist_name          object
danceability        float64
duration_ms           int64
energy              float64
explicit              int64
track_id             object
instrumentalness    float64
key                   int64
liveness            float64
loudness            float64
mode                  int64
track_name           object
popularity            int64
release_date         object
speechiness         float64
tempo               float64
dtype: object
Missing values:
 valence             0
year                0
acousticness        0
artist_name         0
danceability        0
duration_ms         0
energy              0
explicit            0
track_id            0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
track_name          0
popularity          0
release_date        0
speechiness         0
tempo               0
dtype: int64
Shapes after dropping duplicates: (170653, 19)

,valence,year,acousticness,artist_name,danceability,duration_ms,energy,explicit,track_id,instrumentalness,key,liveness,loudness,mode,track_name,popularity,release_date,speechiness,tempo
112125,0.269,1956,0.8420,['Bill Evans'],0.502,491573,0.2370,0,4Ax2J7lvXr2QlUfa7Rlacv,0.540000,7,0.1230,-15.253,1,"No Cover, No Minimum - Take 1: Bonus Track",11,1956,0.0411,133.432
48203,0.784,1975,0.5510,['Los Donneños'],0.562,241347,0.2440,0,2O7chSnV0xD28SehY19Uzb,0.000009,3,0.0698,-7.909,1,Caballo Patas Blancas,40,1975-01-01,0.0498,175.327
54694,0.524,2007,0.0552,['Kid Rock'],0.669,275653,0.6130,0,0xk2pGhKtVFY8bTdozH3bv,0.000000,0,0.1200,-5.537,1,Blue Jeans and a Rosary,51,2007-10-09,0.0267,130.054
141199,0.549,1940,0.6480,['Эрнест Хемингуэй'],0.779,97515,0.0696,1,4OfMLlq7nZqKE7UuZVP6U8,0.000000,7,0.3510,-24.589,1,Часть 109.4 & Часть 110.1 - По ком звонит колокол,0,1940,0.9560,72.232
99743,0.586,1975,0.7230,['Joni Mitchell'],0.553,244800,0.3780,0,3r0Tk9ibA2KT1KiLGIuKXA,0.000750,7,0.0912,-16.506,1,Don't Interrupt the Sorrow,31,1975-11-01,0.0453,78.009

In [55]:
# summary
spotify_2.describe()

,valence,year,acousticness,danceability,duration_ms,energy,explicit,instrumentalness,key,liveness,loudness,mode,popularity,speechiness,tempo
count,170653.000000,170653.000000,170653.000000,170653.000000,1.706530e+05,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000
mean,0.528587,1976.787241,0.502115,0.537396,2.309483e+05,0.482389,0.084575,0.167010,5.199844,0.205839,-11.467990,0.706902,31.431794,0.098393,116.861590
std,0.263171,25.917853,0.376032,0.176138,1.261184e+05,0.267646,0.278249,0.313475,3.515094,0.174805,5.697943,0.455184,21.826615,0.162740,30.708533
min,0.000000,1921.000000,0.000000,0.000000,5.108000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,-60.000000,0.000000,0.000000,0.000000,0.000000
25%,0.317000,1956.000000,0.102000,0.415000,1.698270e+05,0.255000,0.000000,0.000000,2.000000,0.098800,-14.615000,0.000000,11.000000,0.034900,93.421000
50%,0.540000,1977.000000,0.516000,0.548000,2.074670e+05,0.471000,0.000000,0.000216,5.000000,0.136000,-10.580000,1.000000,33.000000,0.045000,114.729000
75%,0.747000,1999.000000,0.893000,0.668000,2.624000e+05,0.703000,0.000000,0.102000,8.000000,0.261000,-7.183000,1.000000,48.000000,0.075600,135.537000
max,1.000000,2020.000000,0.996000,0.988000,5.403500e+06,1.000000,1.000000,1.000000,11.000000,1.000000,3.855000,1.000000,100.000000,0.970000,243.507000

In [58]:
# research questions only concerns songs from 2016 onwards, filter for these specific years to meet limit of database
filtered_spotify_2 = spotify_2[spotify_2["year"] >= 2016]

# filter for columns related to research question due to database constraints
cleaned_spotify_2 = filtered_spotify_2[["track_id", "danceability", "valence", "energy", "tempo", "year"]]

# round to 3 decimals
cleaned_spotify_2[["danceability", "valence", "energy", "tempo"]] = cleaned_spotify_2[["danceability", "valence", "energy", "tempo"]].round(3)

cleaned_spotify_2.head()
print(cleaned_spotify_2.shape)
print(cleaned_spotify_2.describe())

(9871, 6)
       danceability      valence       energy        tempo         year
count   9871.000000  9871.000000  9871.000000  9871.000000  9871.000000
mean       0.643986     0.451670     0.602370   120.527127  2018.042853
std        0.171375     0.232385     0.205164    30.764615     1.395857
min        0.000000     0.000000     0.000000     0.000000  2016.000000
25%        0.546000     0.272000     0.480500    96.133000  2017.000000
50%        0.664000     0.442000     0.622000   120.078000  2018.000000
75%        0.768000     0.621000     0.749000   141.915000  2019.000000
max        0.985000     0.982000     1.000000   220.099000  2020.000000

/tmp/ipykernel_5769/3527078481.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_spotify_2[["danceability", "valence", "energy", "tempo"]] = cleaned_spotify_2[["danceability", "valence", "energy", "tempo"]].round(3)

In [59]:
# check overlap between spotify 1 and spotify 2
overlap = cleaned_spotify_1[cleaned_spotify_1["track_id"].isin(cleaned_spotify_2["track_id"])].shape[0]
print(overlap)

1858

In [60]:
spotify_audible_features = cleaned_spotify_1.merge(cleaned_spotify_2[["track_id", "year"]], on=['track_id'], how="inner")
print(spotify_audible_features.shape)
print(spotify_audible_features.describe())

(1858, 7)
       danceability      valence       energy        tempo       streams  \
count   1858.000000  1858.000000  1858.000000  1858.000000  1.858000e+03
mean       0.699266     0.475125     0.621809   122.878793  1.503641e+08
std        0.136924     0.219766     0.159170    30.049936  2.985478e+08
min        0.153000     0.036000     0.028000    54.747000  2.580512e+06
25%        0.618000     0.303000     0.524000    97.812500  1.215400e+07
50%        0.716500     0.467000     0.632000   120.511500  4.221403e+07
75%        0.797000     0.645000     0.740000   144.928750  1.583216e+08
max        0.980000     0.970000     0.972000   207.476000  3.528450e+09

              year
count  1858.000000
mean   2018.562433
std       1.194868
min    2016.000000
25%    2018.000000
50%    2019.000000
75%    2020.000000
max    2020.000000

In [63]:
spotify_audible_features.isnull().sum()

track_id        0
danceability    0
valence         0
energy          0
tempo           0
streams         0
year            0
dtype: int64

In [64]:
# save cleaned dataset to csv
spotify_audible_features.to_csv("processed/spotify_audible_features.csv", index=False)