In [28]:
# import libraries
import pandas as pd

In [29]:
# load dataset
df = pd.read_csv("raw/artist.csv")

df.head()

,Unnamed: 0,Artist Name,Lead Streams,Feats,Tracks,One Billion,100 Million,Last Updated
0,1,Drake,"50,162,292,808","19,246,513,666",262,6,130,19.09.22
1,2,Bad Bunny,"44,369,032,140","5,391,990,975",163,5,118,20.09.22
2,3,Ed Sheeran,"38,153,682,361","2,791,278,201",240,10,62,19.09.22
3,4,The Weeknd,"34,767,779,741","4,288,903,657",186,8,72,19.09.22
4,5,Taylor Swift,"32,596,728,109","424,053,296",323,1,96,20.09.22

In [30]:
# check data types
df.dtypes

Unnamed: 0       int64
Artist Name     object
Lead Streams    object
Feats           object
Tracks          object
One Billion     object
100 Million     object
Last Updated    object
dtype: object

In [31]:
# drop index and last updated column
df = df[["Artist Name", "Lead Streams", "Feats", "Tracks", "One Billion", "100 Million"]]

print(df.columns.tolist())

['Artist Name', 'Lead Streams', 'Feats', 'Tracks', 'One Billion', '100 Million']

In [32]:
# rename columns to be all lowercase and remove space inbetween words
df.columns = df.columns.str.lower().str.replace(' ', '_')

print(df.columns.tolist())

['artist_name', 'lead_streams', 'feats', 'tracks', 'one_billion', '100_million']

In [34]:
# check for missing values
missing_values = df.isnull().sum()
print(missing_values)

artist_name     0
lead_streams    0
feats           0
tracks          0
one_billion     0
100_million     0
dtype: int64

In [55]:
# remove commas from lead streams and feats and
df["lead_streams"] = df["lead_streams"].str.replace(',', '')
df["feats"] = df["feats"].str.replace(',', '')
df["tracks"] = df["tracks"].str.replace(',','')

In [56]:
print(df.head(3))

  artist_name lead_streams        feats tracks one_billion 100_million
0       Drake  50162292808  19246513666    262           6         130
1   Bad Bunny  44369032140   5391990975    163           5         118
2  Ed Sheeran  38153682361   2791278201    240          10          62

In [57]:
# found weird values in dataset that need to be removed
print(df[df['lead_streams'] == 'Lead Streams'])

clean_df = df[df['lead_streams'] != 'Lead Streams']
print(clean_df[clean_df['lead_streams'] == 'Lead Streams'])

Empty DataFrame
Columns: [artist_name, lead_streams, feats, tracks, one_billion, 100_million]
Index: []
Empty DataFrame
Columns: [artist_name, lead_streams, feats, tracks, one_billion, 100_million]
Index: []

In [61]:
# change data types from string to int
df[["lead_streams", "feats", "tracks", "one_billion", "100_million"]] = clean_df[["lead_streams", "feats", "tracks", "one_billion", "100_million"]].astype(int)

df.head()

    artist_name  lead_streams        feats  tracks  one_billion  100_million
0         Drake   50162292808  19246513666     262            6          130
1     Bad Bunny   44369032140   5391990975     163            5          118
2    Ed Sheeran   38153682361   2791278201     240           10           62
3    The Weeknd   34767779741   4288903657     186            8           72
4  Taylor Swift   32596728109    424053296     323            1           96

In [64]:
print(df.describe())
print(df.dtypes)
print(df.shape)

       lead_streams         feats        tracks  one_billion  100_million
count  1.000000e+03  1.000000e+03   1000.000000  1000.000000  1000.000000
mean   4.291403e+09  8.619085e+08    267.901000     0.360000     8.977000
std    4.827224e+09  1.742020e+09    620.636208     1.047615    11.443226
min    1.420597e+09  0.000000e+00     11.000000     0.000000     0.000000
25%    1.850499e+09  1.372302e+07     86.750000     0.000000     3.000000
50%    2.613283e+09  1.833078e+08    147.500000     0.000000     5.000000
75%    4.625016e+09  7.977515e+08    252.250000     0.000000    10.000000
max    5.016229e+10  1.924651e+10  11475.000000    10.000000   130.000000
artist_name     object
lead_streams     int64
feats            int64
tracks           int64
one_billion      int64
100_million      int64
dtype: object
(1000, 6)

In [65]:
# save csv
df.to_csv("processed/artist_clean.csv", index=False)