In [1]:
# load libaries

import pandas as pd
import numpy as np

In [13]:
# load datasets

spotify_1 = pd.read_csv("raw/spotify_1.csv")
spotify_2 = pd.read_csv("raw/spotify_2.csv")

# list columns of all three datasets
print("Spotify 1 Columns: \n", spotify_1.columns.tolist(), "\n Spotify 2 Columns:\n", spotify_2.columns.tolist())

Spotify 1 Columns:
 ['id', 'artist_names', 'track_name', 'source', 'key', 'mode', 'time_signature', 'danceability', 'energy', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'loudness', 'tempo', 'duration_ms', 'weeks_on_chart', 'streams']
 Spotify 2 Columns:
 ['valence', 'year', 'acousticness', 'artists', 'danceability', 'duration_ms', 'energy', 'explicit', 'id', 'instrumentalness', 'key', 'liveness', 'loudness', 'mode', 'name', 'popularity', 'release_date', 'speechiness', 'tempo']

In [14]:
# renaming columns for standardizing
spotify_1 = spotify_1.rename(columns={"id": "track_id"})
spotify_2 = spotify_2.rename(columns={"id": "track_id"})

spotify_1 = spotify_1.rename(columns={"artist_names": "artist_name"})
spotify_2 = spotify_2.rename(columns={"artists": "artist_name"})

spotify_2 = spotify_2.rename(columns={"name": "track_name"})

print(spotify_1.columns, spotify_2.columns)

print(spotify_1.shape, spotify_2.shape)

Index(['track_id', 'artist_name', 'track_name', 'source', 'key', 'mode',
       'time_signature', 'danceability', 'energy', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'loudness',
       'tempo', 'duration_ms', 'weeks_on_chart', 'streams'],
      dtype='object') Index(['valence', 'year', 'acousticness', 'artist_name', 'danceability',
       'duration_ms', 'energy', 'explicit', 'track_id', 'instrumentalness',
       'key', 'liveness', 'loudness', 'mode', 'track_name', 'popularity',
       'release_date', 'speechiness', 'tempo'],
      dtype='object')
(6513, 19) (170653, 19)

In [15]:
# CLEANING: Spotify 1 - Spotify Top Songs And Audio Features

# check data types
print(spotify_1.dtypes)

# check for missing values
missing_values_1 = spotify_1.isnull().sum()
print("Missing values:\n", missing_values_1)

# drop missing values
spotify_1 = spotify_1.dropna()

# check for duplicates
spotify_1 = spotify_1.drop_duplicates()
print("Shapes after dropping duplicates:", spotify_1.shape)

spotify_1.sample(5)

track_id             object
artist_name          object
track_name           object
source               object
key                  object
mode                 object
time_signature       object
danceability        float64
energy              float64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
loudness            float64
tempo               float64
duration_ms           int64
weeks_on_chart        int64
streams               int64
dtype: object
Missing values:
 track_id            0
artist_name         0
track_name          0
source              0
key                 0
mode                0
time_signature      0
danceability        0
energy              0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
loudness            0
tempo               0
duration_ms         0
weeks_on_chart      0
streams             0
dtype: int64
Shapes after dropping duplicates: (6513, 19)

,track_id,artist_name,track_name,source,key,mode,time_signature,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,loudness,tempo,duration_ms,weeks_on_chart,streams
5498,6c1QaQHdDhtFMfUkhueuXK,Red Velvet - IRENE & SEULGI,Monster,SM Entertainment,E,Minor,4 beats,0.631,0.748,0.0488,0.21200,0.000000,0.5370,0.351,-2.569,115.665,178413,1,5030481
3399,43NqTeL8pgBxKHPMiJKUP5,Myke Towers,Girl,2020 One World Music & Casablanca Records | Po...,F#/Gb,Major,4 beats,0.733,0.708,0.0937,0.03250,0.000327,0.3240,0.694,-4.957,93.021,186427,6,36889213
5420,6WbTTAGKrQtCQvmc5BuYfh,Megan Thee Stallion,Girls in the Hood,300 Entertainment,F#/Gb,Major,4 beats,0.821,0.863,0.3530,0.00824,0.000000,0.0377,0.874,-3.159,180.013,154324,1,4577209
1421,1jQsKN68yE94tMYml0wHMd,Big Sean,Jump Out The Window,Getting Out Our Dreams Inc. (G.O.O.D.) Music /...,C#/Db,Major,4 beats,0.747,0.704,0.0986,0.13600,0.000000,0.1310,0.494,-6.743,136.936,213693,1,4485894
5567,6hH6QJ9ZAO0Z6m7PfvLoXW,ROSALÍA,CHICKEN TERIYAKI,Columbia,D,Major,4 beats,0.788,0.400,0.1150,0.45400,0.000141,0.0686,0.558,-6.454,97.936,122227,1,5951779

In [16]:
# summary
spotify_1.describe()

,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,loudness,tempo,duration_ms,weeks_on_chart,streams
count,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6.513000e+03
mean,0.681731,0.636522,0.121933,0.236761,0.012469,0.180168,0.492412,-6.350667,122.117244,202566.684170,13.614924,1.089647e+08
std,0.141787,0.164813,0.113441,0.244784,0.075151,0.138054,0.227001,2.536114,29.416097,49199.592333,24.084051,2.276695e+08
min,0.150000,0.021800,0.023200,0.000008,0.000000,0.019700,0.032000,-34.475000,46.718000,30133.000000,1.000000,2.525159e+06
25%,0.591000,0.534000,0.044000,0.044400,0.000000,0.097400,0.316000,-7.564000,98.007000,173038.000000,1.000000,8.695060e+06
50%,0.698000,0.651000,0.072200,0.145000,0.000000,0.124000,0.489000,-5.983000,120.034000,198367.000000,4.000000,2.712856e+07
75%,0.785000,0.759000,0.163000,0.356000,0.000041,0.219000,0.669000,-4.673000,142.025000,226003.000000,16.000000,9.951456e+07
max,0.985000,0.989000,0.966000,0.994000,0.953000,0.977000,0.982000,1.509000,212.117000,690732.000000,367.000000,3.528450e+09

In [24]:
# filter for columns related to research question due to database constraints
cleaned_spotify_1 = spotify_1[["track_id", "instrumentalness" , "danceability", "liveness", "valence", "energy", "acousticness", "tempo", "streams"]]
print(cleaned_spotify_1.shape)

(6513, 9)

In [25]:
# CLEANING: Spotify 2 - Spotify Dataset 1921-2020 
# check data types
print(spotify_2.dtypes)

# check for missing values
missing_values_2 = spotify_2.isnull().sum()
print("Missing values:\n", missing_values_2)

# drop missing values
spotify_2 = spotify_2.dropna()

# check for duplicates
spotify_2 = spotify_2.drop_duplicates()
print("Shapes after dropping duplicates:", spotify_2.shape)

spotify_2.sample(5)

valence             float64
year                  int64
acousticness        float64
artist_name          object
danceability        float64
duration_ms           int64
energy              float64
explicit              int64
track_id             object
instrumentalness    float64
key                   int64
liveness            float64
loudness            float64
mode                  int64
track_name           object
popularity            int64
release_date         object
speechiness         float64
tempo               float64
dtype: object
Missing values:
 valence             0
year                0
acousticness        0
artist_name         0
danceability        0
duration_ms         0
energy              0
explicit            0
track_id            0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
track_name          0
popularity          0
release_date        0
speechiness         0
tempo               0
dtype: int64
Shapes after dropping duplicates: (170653, 19)

,valence,year,acousticness,artist_name,danceability,duration_ms,energy,explicit,track_id,instrumentalness,key,liveness,loudness,mode,track_name,popularity,release_date,speechiness,tempo
151963,0.531,2001,0.000056,['Sodom'],0.253,356920,0.8160,0,58SUPk63baVqZ44Yko0wWL,0.0639,2,0.0865,-7.326,1,Napalm in the Morning,46,2001-10-22,0.0506,202.073
60705,0.740,1948,0.569000,['Трумен Капоте'],0.639,134700,0.1360,1,1rb2eYDdwsjQqHYdRt86ZY,0.0000,1,0.1950,-15.973,1,"Часть 19.12 - Другие голоса, другие комнаты",0,1948,0.9520,166.882
116898,0.901,1980,0.272000,['Paul McCartney'],0.663,350747,0.7110,0,6dtZuW3qCqBvY7oeKCzQF7,0.0102,0,0.5660,-8.435,0,Check My Machine - Edit / Remastered 2011,40,1980-05-16,0.0322,81.720
80526,0.789,1961,0.045300,['Del Shannon'],0.599,142973,0.5720,0,1QuXP2TaFPEFQKgv4uBDSB,0.0000,8,0.1900,-11.303,0,His Latest Flame,22,1961-01-01,0.0683,96.150
43255,0.493,1950,0.966000,['George Shearing'],0.649,162653,0.0671,0,1w2e8Gqt4AUwtkebIGPtMo,0.9050,7,0.1080,-24.242,1,As Long As There's Music,2,1950-01-01,0.0372,112.753

In [26]:
# summary
spotify_2.describe()

,valence,year,acousticness,danceability,duration_ms,energy,explicit,instrumentalness,key,liveness,loudness,mode,popularity,speechiness,tempo
count,170653.000000,170653.000000,170653.000000,170653.000000,1.706530e+05,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000,170653.000000
mean,0.528587,1976.787241,0.502115,0.537396,2.309483e+05,0.482389,0.084575,0.167010,5.199844,0.205839,-11.467990,0.706902,31.431794,0.098393,116.861590
std,0.263171,25.917853,0.376032,0.176138,1.261184e+05,0.267646,0.278249,0.313475,3.515094,0.174805,5.697943,0.455184,21.826615,0.162740,30.708533
min,0.000000,1921.000000,0.000000,0.000000,5.108000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,-60.000000,0.000000,0.000000,0.000000,0.000000
25%,0.317000,1956.000000,0.102000,0.415000,1.698270e+05,0.255000,0.000000,0.000000,2.000000,0.098800,-14.615000,0.000000,11.000000,0.034900,93.421000
50%,0.540000,1977.000000,0.516000,0.548000,2.074670e+05,0.471000,0.000000,0.000216,5.000000,0.136000,-10.580000,1.000000,33.000000,0.045000,114.729000
75%,0.747000,1999.000000,0.893000,0.668000,2.624000e+05,0.703000,0.000000,0.102000,8.000000,0.261000,-7.183000,1.000000,48.000000,0.075600,135.537000
max,1.000000,2020.000000,0.996000,0.988000,5.403500e+06,1.000000,1.000000,1.000000,11.000000,1.000000,3.855000,1.000000,100.000000,0.970000,243.507000

In [27]:
# research questions only concerns songs from 2010 onwards, filter for these specific years to meet limit of database
filtered_spotify_2 = spotify_2[spotify_2["year"] >= 2010]

# filter for columns related to research question due to database constraints
cleaned_spotify_2 = filtered_spotify_2[["track_id", "instrumentalness" , "danceability", "liveness", "valence", "energy", "acousticness", "tempo", "year"]]


print(cleaned_spotify_2.shape)
print(cleaned_spotify_2.describe())

(21804, 9)
       instrumentalness  danceability      liveness       valence  \
count      21804.000000  21804.000000  21804.000000  21804.000000
mean           0.080806      0.606309      0.188530      0.460530
std            0.235061      0.170930      0.153838      0.240829
min            0.000000      0.000000      0.000000      0.000000
25%            0.000000      0.502750      0.097100      0.272000
50%            0.000002      0.619000      0.124000      0.447000
75%            0.000768      0.732000      0.231000      0.641000
max            1.000000      0.986000      0.989000      0.993000

             energy  acousticness         tempo          year
count  21804.000000  21804.000000  21804.000000  21804.000000
mean       0.629218      0.259982    121.160507   2015.004403
std        0.219571      0.292144     30.327837      3.181665
min        0.000020      0.000000      0.000000   2010.000000
25%        0.496000      0.024200     97.120500   2012.000000
50%        0.657000      0.132000    121.011000   2015.000000
75%        0.799000      0.426000    140.266000   2018.000000
max        1.000000      0.996000    220.099000   2020.000000

In [28]:
# check overlap between spotify 1 and spotify 2
overlap = cleaned_spotify_1[cleaned_spotify_1["track_id"].isin(cleaned_spotify_2["track_id"])].shape[0]
print(overlap)

1966

In [29]:
spotify_audible_features = cleaned_spotify_1.merge(cleaned_spotify_2[["track_id","year"]], on=['track_id'], how="inner")
print(spotify_audible_features.shape)
print(spotify_audible_features.describe())

(1966, 10)
       instrumentalness  danceability     liveness      valence       energy  \
count       1966.000000   1966.000000  1966.000000  1966.000000  1966.000000
mean           0.010579      0.694417     0.172366     0.475903     0.621398
std            0.065323      0.138298     0.126259     0.220232     0.160899
min            0.000000      0.153000     0.021500     0.036300     0.027900
25%            0.000000      0.611250     0.096825     0.304000     0.523000
50%            0.000000      0.710500     0.123000     0.465500     0.632000
75%            0.000022      0.793000     0.204000     0.645000     0.740000
max            0.918000      0.980000     0.908000     0.970000     0.972000

       acousticness        tempo       streams         year
count   1966.000000  1966.000000  1.966000e+03  1966.000000
mean       0.222124   122.306625  1.515278e+08  2018.252798
std        0.238278    29.964930  2.984120e+08     1.781065
min        0.000042    54.747000  2.580512e+06  2010.000000
25%        0.040225    97.028750  1.206419e+07  2017.000000
50%        0.134000   120.054500  4.199005e+07  2019.000000
75%        0.323000   143.986750  1.587913e+08  2020.000000
max        0.978000   207.476000  3.528450e+09  2020.000000

In [30]:
# save cleaned dataset to csv
spotify_audible_features.to_csv("processed/spotify_audible_features.csv", index=False)