In [36]:
# load libaries

import pandas as pd
import numpy as np

In [48]:
# load datasets

spotify_1 = pd.read_csv("raw/spotify_1.csv")
spotify_2 = pd.read_csv("raw/spotify_2.csv")
spotify_3 = pd.read_csv("raw/spotify_3.csv")

# list columns of all three datasets
print("Spotify 1 Columns: \n", spotify_1.columns.tolist(), "\n Spotify 2 Columns:\n", spotify_2.columns.tolist(), "\n Spotify 3 Columns:\n", spotify_3.columns.tolist())

Spotify 1 Columns:
 ['id', 'artist_names', 'track_name', 'source', 'key', 'mode', 'time_signature', 'danceability', 'energy', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'loudness', 'tempo', 'duration_ms', 'weeks_on_chart', 'streams']
 Spotify 2 Columns:
 ['track_id', 'track_name', 'track_number', 'track_popularity', 'track_duration_ms', 'explicit', 'artist_name', 'artist_popularity', 'artist_followers', 'artist_genres', 'album_id', 'album_name', 'album_release_date', 'album_total_tracks', 'album_type']
 Spotify 3 Columns:
 ['valence', 'year', 'acousticness', 'artists', 'danceability', 'duration_ms', 'energy', 'explicit', 'id', 'instrumentalness', 'key', 'liveness', 'loudness', 'mode', 'name', 'popularity', 'release_date', 'speechiness', 'tempo']

In [51]:
# renaming columns for standardizing
spotify_1 = spotify_1.rename(columns={"id": "track_id"})
spotify_3 = spotify_3.rename(columns={"id": "track_id"})

spotify_1 = spotify_1.rename(columns={"artist_names": "artist_name"})
spotify_3 = spotify_3.rename(columns={"artists": "artist_name"})

spotify_3 = spotify_3.rename(columns={"name": "track_name"})

print(spotify_1.columns, spotify_2.columns, spotify_3.columns)

print(spotify_1.shape, spotify_2.shape, spotify_3.shape)

Index(['track_id', 'artist_name', 'track_name', 'source', 'key', 'mode',
       'time_signature', 'danceability', 'energy', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'loudness',
       'tempo', 'duration_ms', 'weeks_on_chart', 'streams'],
      dtype='object') Index(['track_id', 'track_name', 'track_number', 'track_popularity',
       'track_duration_ms', 'explicit', 'artist_name', 'artist_popularity',
       'artist_followers', 'artist_genres', 'album_id', 'album_name',
       'album_release_date', 'album_total_tracks', 'album_type'],
      dtype='object') Index(['valence', 'year', 'acousticness', 'artist_name', 'danceability',
       'duration_ms', 'energy', 'explicit', 'track_id', 'instrumentalness',
       'key', 'liveness', 'loudness', 'mode', 'track_name', 'popularity',
       'release_date', 'speechiness', 'tempo'],
      dtype='object')
(6513, 19) (8778, 15) (170653, 19)

In [57]:
# CLEANING: Spotify 1 - Spotify Top Songs And Audio Features

# check data types
print(spotify_1.dtypes)

# check for missing values
missing_values_1 = spotify_1.isnull().sum()
print("Missing values:\n", missing_values_1)

# check for duplicates
spotify_1 = spotify_1.drop_duplicates()
print("Shapes after dropping duplicates:", spotify_1.shape)

spotify_1.sample(5)

track_id             object
artist_name          object
track_name           object
source               object
key                  object
mode                 object
time_signature       object
danceability        float64
energy              float64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
loudness            float64
tempo               float64
duration_ms           int64
weeks_on_chart        int64
streams               int64
dtype: object
Missing values:
 track_id            0
artist_name         0
track_name          0
source              0
key                 0
mode                0
time_signature      0
danceability        0
energy              0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
loudness            0
tempo               0
duration_ms         0
weeks_on_chart      0
streams             0
dtype: int64
Shapes after dropping duplicates: (6513, 19)

,track_id,artist_name,track_name,source,key,mode,time_signature,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,loudness,tempo,duration_ms,weeks_on_chart,streams
1571,1uN0f4NqMDcReSwXO6PLuG,Rihanna,Where Have You Been,Def Jam Recordings,C,Minor,4 beats,0.719,0.847,0.0916,0.00201,0.020400,0.223,0.444,-6.340,127.963,242680,1,8033394
4544,5PTG6rrL6EPFD9E2QMI2pl,Famous Dex,JAPAN,300 Entertainment,F#/Gb,Major,4 beats,0.733,0.678,0.4380,0.12100,0.000000,0.344,0.841,-7.771,175.985,142000,20,123148995
2364,2oiixB9QMIzhWaHGVlQx4g,"Yandel, Feid",Yandel 150,La Leyenda LLC,F#/Gb,Minor,4 beats,0.783,0.729,0.0691,0.04920,0.000272,0.100,0.580,-3.549,167.968,216148,1,12150584
6249,7gwwt1IaAWwmB7af0AcuBM,Harry Nach,Tak Tiki Tak,Sony Music Entertainment Chile S.A,B,Minor,4 beats,0.801,0.579,0.0813,0.33300,0.000355,0.172,0.231,-4.780,99.994,212406,17,73511877
4266,54bFM56PmE4YLRnqpW6Tha,Billie Eilish,Therefore I Am,Darkroom/Interscope Records,B,Minor,4 beats,0.889,0.340,0.0697,0.21800,0.130000,0.055,0.716,-7.773,94.009,174321,31,401355680

In [66]:
# summary
spotify_1.describe()

,danceability,energy,speechiness,acousticness,instrumentalness,liveness,valence,loudness,tempo,duration_ms,weeks_on_chart,streams
count,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6513.000000,6.513000e+03
mean,0.681731,0.636522,0.121933,0.236761,0.012469,0.180168,0.492412,-6.350667,122.117244,202566.684170,13.614924,1.089647e+08
std,0.141787,0.164813,0.113441,0.244784,0.075151,0.138054,0.227001,2.536114,29.416097,49199.592333,24.084051,2.276695e+08
min,0.150000,0.021800,0.023200,0.000008,0.000000,0.019700,0.032000,-34.475000,46.718000,30133.000000,1.000000,2.525159e+06
25%,0.591000,0.534000,0.044000,0.044400,0.000000,0.097400,0.316000,-7.564000,98.007000,173038.000000,1.000000,8.695060e+06
50%,0.698000,0.651000,0.072200,0.145000,0.000000,0.124000,0.489000,-5.983000,120.034000,198367.000000,4.000000,2.712856e+07
75%,0.785000,0.759000,0.163000,0.356000,0.000041,0.219000,0.669000,-4.673000,142.025000,226003.000000,16.000000,9.951456e+07
max,0.985000,0.989000,0.966000,0.994000,0.953000,0.977000,0.982000,1.509000,212.117000,690732.000000,367.000000,3.528450e+09

In [71]:
cleaned_spotify_1 = spotify_1[["track_id", "instrumentalness" , "danceability", "liveness", "valence", "loudness", "energy", "acousticness", "tempo", "streams"]]
print(cleaned_spotify_1.shape)

(6513, 10)

In [72]:
# check for overlaps in data
shared_between_1_2 = spotify_1[spotify_1["track_id"].isin(spotify_3["track_id"])].shape[0]
print(shared_between_1_2, "tracks overlapping in dataset 1 and 2")

shared_between_1_3 = spotify_1[spotify_1["track_id"].isin(spotify_2["track_id"])].shape[0]
print(shared_between_1_3, "tracks overlapping in dataset 1 and 3")

2090 tracks overlapping in dataset 1 and 2
1557 tracks overlapping in dataset 1 and 3

In [ ]:
# CLEANING: Spotify 2 - Spotify Dataset 1921-2020

In [39]:
# check for missing values
missing_values_1 = spotify_1.isnull().sum()
print("Missing values:\n", missing_values_1)

missing_values_2 = spotify_2.isnull().sum()
print("Missing values:\n", missing_values_2)

missing_values_3 = spotify_3.isnull().sum()
print("Missing values:\n", missing_values_3)

Missing values:
 track_id            0
artist_names        0
track_name          0
source              0
key                 0
mode                0
time_signature      0
danceability        0
energy              0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
loudness            0
tempo               0
duration_ms         0
weeks_on_chart      0
streams             0
dtype: int64
Missing values:
 track_id              0
track_name            2
track_number          0
track_popularity      0
track_duration_ms     0
explicit              0
artist_name           4
artist_popularity     4
artist_followers      4
artist_genres         4
album_id              0
album_name            2
album_release_date    0
album_total_tracks    0
album_type            0
dtype: int64
Missing values:
 valence             0
year                0
acousticness        0
artists             0
danceability        0
duration_ms         0
energy              0
explicit            0
track_id            0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
name                0
popularity          0
release_date        0
speechiness         0
tempo               0
dtype: int64

In [40]:
# Drop rows with missing values
spotify_2 = spotify_2.dropna()
print("Shape after dropping missing values:", spotify_2.shape)

Shape after dropping missing values: (8772, 15)

In [41]:
# Remove duplicates
spotify_1 = spotify_1.drop_duplicates()
spotify_2 = spotify_2.drop_duplicates()
spotify_3 = spotify_3.drop_duplicates()

print("Shapes after dropping duplicates:", spotify_1.shape, spotify_2.shape, spotify_3.shape)

Shapes after dropping duplicates: (6513, 19) (8772, 15) (170653, 19)

In [42]:
# Check data types
print("\nData types:")
print(spotify_1.dtypes)
print(spotify_2.dtypes)
print(spotify_3.dtypes)

Data types:
track_id             object
artist_names         object
track_name           object
source               object
key                  object
mode                 object
time_signature       object
danceability        float64
energy              float64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
loudness            float64
tempo               float64
duration_ms           int64
weeks_on_chart        int64
streams               int64
dtype: object
track_id               object
track_name             object
track_number            int64
track_popularity        int64
track_duration_ms       int64
explicit                 bool
artist_name            object
artist_popularity     float64
artist_followers      float64
artist_genres          object
album_id               object
album_name             object
album_release_date     object
album_total_tracks      int64
album_type             object
dtype: object
valence             float64
year                  int64
acousticness        float64
artists              object
danceability        float64
duration_ms           int64
energy              float64
explicit              int64
track_id             object
instrumentalness    float64
key                   int64
liveness            float64
loudness            float64
mode                  int64
name                 object
popularity            int64
release_date         object
speechiness         float64
tempo               float64
dtype: object

In [43]:
# check for overlaps in tracks

shared_between_1_2 = spotify_1[spotify_1["track_id"].isin(spotify_2["track_id"])].shape[0]
print(shared_between_1_2, "tracks overlapping in dataset 1 and 2")

shared_between_1_3 = spotify_1[spotify_1["track_id"].isin(spotify_3["track_id"])].shape[0]
print(shared_between_1_3, "tracks overlapping in dataset 1 and 3")

shared_between_2_3 = spotify_2[spotify_2["track_id"].isin(spotify_3["track_id"])].shape[0]
print(shared_between_2_3, "tracks overlapping in dataset 2 and 3")

1556 tracks overlapping in dataset 1 and 2
2090 tracks overlapping in dataset 1 and 3
2866 tracks overlapping in dataset 2 and 3

In [44]:
# merging

spotify_1_2 = spotify_1.merge(spotify_2, on="track_id", how="outer", suffixes=("_1", "_2"))
spotify_1_2_3 = spotify_3.merge(spotify_1_2, on="track_id", how="outer", suffixes=("", "_3"))

print(spotify_1_2_3.shape)
print(spotify_1_2_3.columns)

(180182, 51)
Index(['valence', 'year', 'acousticness', 'artists', 'danceability',
       'duration_ms', 'energy', 'explicit', 'track_id', 'instrumentalness',
       'key', 'liveness', 'loudness', 'mode', 'name', 'popularity',
       'release_date', 'speechiness', 'tempo', 'artist_names', 'track_name_1',
       'source', 'key_3', 'mode_3', 'time_signature', 'danceability_3',
       'energy_3', 'speechiness_3', 'acousticness_3', 'instrumentalness_3',
       'liveness_3', 'valence_3', 'loudness_3', 'tempo_3', 'duration_ms_3',
       'weeks_on_chart', 'streams', 'track_name_2', 'track_number',
       'track_popularity', 'track_duration_ms', 'explicit_3', 'artist_name',
       'artist_popularity', 'artist_followers', 'artist_genres', 'album_id',
       'album_name', 'album_release_date', 'album_total_tracks', 'album_type'],
      dtype='object')

In [30]:
spotify_1_2_3.head()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,track_id,instrumentalness,...,explicit_3,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type
0,0.555,1978.0,0.0131,['Blondie'],0.256,182347.0,0.895,0.0,000G1xMMuwxNHmwVsBdtj1,0.000106,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.146,2008.0,0.4690,['Atmosphere'],0.797,180160.0,0.898,1.0,000GyYHG4uWmlXieKLij8u,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.494,1953.0,0.9800,['Talat Mahmood'],0.277,206972.0,0.145,0.0,000Npgk5e2SgwGaIsN3ztv,0.879000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.854,1954.0,0.7950,"['Meade ""Lux"" Lewis']",0.685,314667.0,0.483,0.0,000ZxLGm7jDlWCHtcXSeBe,0.878000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.969,1954.0,0.6560,['Trio Maravilla'],0.788,179747.0,0.808,0.0,000jBcNljWTnyjB4YO7ojf,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
merged_missing_values = spotify_1_2_3.isnull().sum()
print("Missing values:\n", merged_missing_values)

cleaned_spotify = spotify_1_2_3.dropna()
print("Shape after dropping missing values:", cleaned_spotify.shape)

Missing values:
 valence                 9529
year                    9529
acousticness            9529
artists                 9529
danceability            9529
duration_ms             9529
energy                  9529
explicit                9529
track_id                   0
instrumentalness        9529
key                     9529
liveness                9529
loudness                9529
mode                    9529
name                    9529
popularity              9529
release_date            9529
speechiness             9529
tempo                   9529
artist_names          173669
track_name_1          173669
source                173669
key_3                 173669
mode_3                173669
time_signature        173669
danceability_3        173669
energy_3              173669
speechiness_3         173669
acousticness_3        173669
instrumentalness_3    173669
liveness_3            173669
valence_3             173669
loudness_3            173669
tempo_3               173669
duration_ms_3         173669
weeks_on_chart        173669
streams               173669
track_name_2          171410
track_number          171410
track_popularity      171410
track_duration_ms     171410
explicit_3            171410
artist_name           171410
artist_popularity     171410
artist_followers      171410
artist_genres         171410
album_id              171410
album_name            171410
album_release_date    171410
album_total_tracks    171410
album_type            171410
dtype: int64
Shape after dropping missing values: (756, 51)

In [32]:
cleaned_spotify.describe()

,valence,year,acousticness,danceability,duration_ms,energy,explicit,instrumentalness,key,liveness,...,tempo_3,duration_ms_3,weeks_on_chart,streams,track_number,track_popularity,track_duration_ms,artist_popularity,artist_followers,album_total_tracks
count,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,756.000000,...,756.000000,756.000000,756.000000,7.560000e+02,756.000000,756.000000,756.000000,756.000000,7.560000e+02,756.000000
mean,0.455300,2016.820106,0.236196,0.674700,210120.789683,0.610644,0.419312,0.012532,5.355820,0.163496,...,119.257775,210120.576720,37.042328,2.922427e+08,5.085979,68.575397,210122.048942,80.891534,4.313656e+07,11.785714
std,0.224503,5.502983,0.253291,0.143851,48536.278363,0.167602,0.493773,0.067376,3.683736,0.119851,...,27.651787,48536.666548,46.935106,4.344776e+08,4.413917,18.883915,48536.094367,9.895688,4.309859e+07,7.304474
min,0.039700,1971.000000,0.000060,0.153000,78681.000000,0.056100,0.000000,0.000000,0.000000,0.021500,...,62.446000,78681.000000,1.000000,2.638669e+06,1.000000,0.000000,78680.000000,44.000000,1.356100e+04,1.000000
25%,0.279250,2017.000000,0.041650,0.584000,180905.500000,0.506000,0.000000,0.000000,1.750000,0.093100,...,97.959000,180905.500000,6.000000,3.144473e+07,1.000000,65.750000,180905.250000,75.000000,8.506651e+06,7.000000
50%,0.450500,2018.000000,0.142000,0.688000,205153.000000,0.619500,0.000000,0.000000,6.000000,0.117500,...,117.223500,205153.000000,23.000000,1.240877e+08,4.000000,73.000000,205152.000000,81.000000,2.611655e+07,13.000000
75%,0.624250,2019.000000,0.347500,0.777250,230848.000000,0.732250,1.000000,0.000036,9.000000,0.193000,...,139.922750,230848.000000,50.000000,3.858233e+08,8.000000,79.000000,230847.750000,88.000000,5.888059e+07,16.000000
max,0.969000,2020.000000,0.978000,0.970000,577199.000000,0.978000,1.000000,0.832000,11.000000,0.914000,...,207.476000,577199.000000,367.000000,3.528450e+09,24.000000,92.000000,577199.000000,100.000000,1.455421e+08,59.000000

In [33]:
cleaned_spotify['is_duplicate'] = cleaned_spotify.duplicated(subset='track_id', keep=False)
print(cleaned_spotify['is_duplicate'].value_counts())

is_duplicate
False    756
Name: count, dtype: int64

/tmp/ipykernel_2245/3792311719.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_spotify['is_duplicate'] = cleaned_spotify.duplicated(subset='track_id', keep=False)

In [34]:
cleaned_spotify.columns

Index(['valence', 'year', 'acousticness', 'artists', 'danceability',
       'duration_ms', 'energy', 'explicit', 'track_id', 'instrumentalness',
       'key', 'liveness', 'loudness', 'mode', 'name', 'popularity',
       'release_date', 'speechiness', 'tempo', 'artist_names', 'track_name_1',
       'source', 'key_3', 'mode_3', 'time_signature', 'danceability_3',
       'energy_3', 'speechiness_3', 'acousticness_3', 'instrumentalness_3',
       'liveness_3', 'valence_3', 'loudness_3', 'tempo_3', 'duration_ms_3',
       'weeks_on_chart', 'streams', 'track_name_2', 'track_number',
       'track_popularity', 'track_duration_ms', 'explicit_3', 'artist_name',
       'artist_popularity', 'artist_followers', 'artist_genres', 'album_id',
       'album_name', 'album_release_date', 'album_total_tracks', 'album_type',
       'is_duplicate'],
      dtype='object')

In [35]:
cleaned_spotify.head()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,track_id,instrumentalness,...,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,is_duplicate
21,0.236,2004.0,0.00121,['The Killers'],0.352,222973.0,0.911,0.0,003vvx7Niy0yvhvHt4a68B,0.000000,...,The Killers,76.0,8006321.0,['alternative rock'],4piJq7R3gjUOxnYs6lDCTg,Hot Fuss,2004,12.0,album,False
65,0.665,2018.0,0.28700,"['Cardi B', 'Chance the Rapper']",0.620,284856.0,0.625,1.0,00B7TZ0Xawar6NZ00JFomN,0.000000,...,Cardi B,81.0,25953771.0,[],4KdtEKjY3Gi0mKiSdy96ML,Invasion of Privacy,2018-04-06,13.0,album,False
452,0.467,2020.0,0.16700,['Dua Lipa'],0.730,221820.0,0.729,0.0,017PF4Q3l4DBUiWoXk4OWT,0.000001,...,Dua Lipa,85.0,46886554.0,['pop'],7fJJK56U9fHixgO0HQkhtI,Future Nostalgia,2020-03-27,11.0,album,False
982,0.531,2020.0,0.44000,['Glass Animals'],0.761,238805.0,0.525,0.0,02MWAaffLxlfxAUY7c5dvx,0.000007,...,Glass Animals,73.0,4568462.0,[],0KTj6k94XZh0c6IEMfxeWV,Dreamland (+ Bonus Levels),2020-08-06,18.0,album,False
1516,0.195,2017.0,0.11300,"['Lana Del Rey', 'A$AP Rocky']",0.359,264038.0,0.600,1.0,03hqMhmCZiNKMSPmVabPLP,0.000001,...,Lana Del Rey,88.0,51821190.0,[],7xYiTrbTL57QO0bb4hXIKo,Lust For Life,2017-07-21,16.0,album,False